### ISSUE TITLE
Bug when using Cell.EditingTemplate

### ISSUE THREAD

**Issue by JohanLarsson** [GuOrg/Gu.Wpf.DataGrid2D#30]
```xml
<DataGrid dataGrid2D:ItemsSource.Array2D="{Binding Array2D}">
    <dataGrid2D:Cell.Template>
        <DataTemplate>
            <TextBlock Text="{Binding StringFormat=E1}" />
        </DataTemplate>
    </dataGrid2D:Cell.Template>
    <dataGrid2D:Cell.EditingTemplate>
        <DataTemplate>
            <TextBox Text="{Binding}" />
        </DataTemplate>
    </dataGrid2D:Cell.EditingTemplate>
</DataGrid>
```

```cs
this.Array2D = new[,] { { 1.0, 2 }, { 3, 4 }, { 5, 6 } };
```

**Comment by FoggyFinder** [comment]
Sadly, but I think there is no bug. It how two-way binding works:

[How to make ListBox editable when bound to a List](https://stackoverflow.com/questions/5793438/how-to-make-listbox-editable-when-bound-to-a-liststring)

**Comment by JohanLarsson** [comment]
Yes, you are right.

**Comment by FoggyFinder** [comment]
Maybe so, but I don't think that changing expected behaviour is good idea.

But certainly it make sense to add possibility to convenience work with cells format (like for #29)

**Comment by JohanLarsson** [comment]
I'll close this then.
