### ISSUE TITLE
.Net Core 3 support

### ISSUE THREAD

**Issue by FoggyFinder** [GuOrg/Gu.Wpf.DataGrid2D#37]

**Comment by JohanLarsson** [comment]
What do we need to do for this? Multitarget and repack?
I'm lagging, have not played with netcore 3 yet.

**Comment by FoggyFinder** [comment]
Yep

**Comment by JohanLarsson** [comment]
Should be easy, I'm a bit busy, do you have time for a PR?

**Comment by FoggyFinder** [comment]
Not right now, but I can do it today
