### ISSUE TITLE
Cells/Row/Column sizes.

### ISSUE THREAD

**Issue by chris-T-hulea** [GuOrg/Gu.Wpf.DataGrid2D#56]
Hi,

I'm using your library for one of my projects and I love it.
My issue is that I need a way to determine the actual size of each cell , or alternatively the size of each row and column.
Do you think there is a way of doing this?

Thank you!

**Comment by JohanLarsson** [comment]
I missed this issue, did you find a solution?

**Comment by chris-T-hulea** [comment]
Not an easy  or pretty one, but I extracted it from code behind. Not good practice, but I'm not too concerned.

**Comment by JohanLarsson** [comment]
Don't worry, code behind is not a crime. Code behind sounds right for view stuff like this.

**Comment by chris-T-hulea** [comment]
Thanks for feedback!
